name: file_transport
version: 0.0.1
publish_to: none
description: File and rolling file transport for revere logger.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  revere:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
