name: file_transport
description: File and rolling file transport for revere logger.
version: 1.1.0

homepage: https://github.com/kumo01GitHub/revere
repository: https://github.com/kumo01GitHub/revere/tree/main/packages/file_transport

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  revere: ^2.0.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
