name: firebase_transport
version: 0.0.1
publish_to: none
description: Firebase Crashlytics/Analytics transport for revere logger.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  revere:
    path: ../core
  firebase_crashlytics: ^3.4.0
  firebase_analytics: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
