name: revere
description: "Core logger package for the revere monorepo. Provides extensible, asynchronous logging for Flutter/Dart projects."
version: 0.0.1

homepage: https://github.com/kumo01GitHub/revere
repository: https://github.com/kumo01GitHub/revere/packages/core

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
