name: websocket_transport
description: WebSocket transport for revere logger.
version: 1.0.0

homepage: https://github.com/kumo01GitHub/revere
repository: https://github.com/kumo01GitHub/revere/tree/main/packages/websocket_transport

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  revere: ^1.0.0

dev_dependencies:
  fake_async: ^1.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
