name: android_log_transport
description: Android Logcat transport for revere logger (via platform channel).
version: 0.0.1

homepage: https://github.com/kumo01GitHub/revere
repository: https://github.com/kumo01GitHub/revere/packages/android_log_transport

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  revere: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.kumo01.revere
        pluginClass: AndroidLogTransportPlugin
        dartPluginClass: AndroidLogTransport
