name: CI / Android Log Transport

on:
  workflow_call:

jobs:
  android_log_transport:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29, 31, 33, 35]
    defaults:
      run:
        working-directory: packages/android_log_transport

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build (dependency resolution)
        run: flutter pub get

      - name: Lint
        run: flutter analyze

      - name: Spec test
        run: flutter test test

      - name: Build example (dependency resolution)
        run: flutter pub get
        working-directory: packages/android_log_transport/example

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Integration test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: cd packages/android_log_transport/example && flutter test integration_test
