name: CI / Swift Log Transport

on:
  workflow_call:

jobs:
  swift_log_transport:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/swift_log_transport

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build (dependency resolution)
        run: flutter pub get

      - name: Lint
        run: flutter analyze

      - name: Spec test
        run: flutter test test

      - name: Build example (dependency resolution)
        run: flutter pub get
        working-directory: packages/swift_log_transport/example

      - name: Integration test
        run: flutter test integration_test
        working-directory: packages/swift_log_transport/example
