name: CI / WebSocket Transport

on:
  workflow_call:
    inputs:
      run_integration_tests:
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      run_integration_tests:
        type: boolean
        default: false
        description: 'Run integration tests'

jobs:
  spec_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/websocket_transport

    steps:
      - uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c

      - name: Build (dependency resolution)
        run: dart pub get

      - name: Lint
        run: dart analyze --fatal-infos --fatal-warnings

      - name: Spec test
        run: dart test --reporter=expanded
